---
title: "Alcohol vs. Happiness: an Investigation into Alcoholism"
author: "Adam, Dillon, Ruben, Nick"
format: html
  html:
    self-contained: true
    code-tools: true
    toc: true
    number-sections: true
    code-fold: true
editor: source
execute:
  error: true
  echo: true
  message: false
  warning: false
---

```{r Setup}
library(tidyverse)
library(here)
alc <- read.csv(here::here("sh_alc_pcap_li.csv"))
happy <- read.csv(here::here("hapiscore_whr.csv"))
```

```{r}
#Data Cleaning
alc <- alc |> 
  rename_with(.fn = ~str_sub(.x,2), 
                          .cols = X1999:X2017)
alc <- alc |> 
  mutate(
    across("1999":"2017", as.numeric)) |> 
  select("country", "1999", "2004", "2009", "2014", "2017")
```

```{r}
# rename columns
happy <- happy |>
  dplyr::rename_with(.fn = ~str_sub(.x, 2),
                     .cols = X2004:X2020)
```

```{r}
#Pivoting Longer
alc_final <- alc |> 
  pivot_longer(cols = `1999`:`2017`,
               names_to = "year",
               values_to = "alcohol_consumption")|>  
  mutate(
    across("year", as.numeric))
```

```{r}
#Pivoting Longer
happy_final <- happy |> 
  pivot_longer(cols = `2004`:`2020`,
               names_to = "year",
               values_to = "happiness_score")|>  
  mutate(
    across("year", as.numeric))
```

```{r}
#Inner Joining the data
final_data <- inner_join(happy_final, alc_final, by = c("year", "country"))
final_data
```

